name: E5-Rclone-Actions-Repo

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: 30 1,13 * * *
  watch:
    types: started
jobs:
  run-it:
    runs-on: ubuntu-latest
    name: zip
    steps:

      - name: Checkout codes
        uses: actions/checkout@v2

      - name: Install rclone #安装rclone
        run: curl https://rclone.org/install.sh | sudo bash

      - name: Add config #解压配置文件
        run: |
         mkdir -p ~/.config/rclone/
         echo -e "${{ secrets.RCLONE_CONFIG }}" > ~/.config/rclone/rclone.conf
     
      - name: Run rclone #运行rclone
        run: |
          
          # 更改时区
          sudo cp /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
          
          # 列出文件(此处不展示)
          echo "列出文件(此处不展示)"
          rclone lsd "onedrive:SonicBit" > "lsd.log"
          rclone mkdir onedrive:/E5-Rclone-Actions-Repo/
          rclone move lsd.log onedrive:/E5-Rclone-Actions-Repo/
          rclone delete onedrive:/E5-Rclone-Actions-Repo/lsd.log
          rclone rmdir onedrive:/E5-Rclone-Actions-Repo/
          
      - name: Commit config #提交配置文件
        run: |
         rm ~/.config/rclone/rclone.conf
         echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
         git config --global user.email "144663295+ihzazuhairnawan@users.noreply.github.com"
         git config --global user.name "ihzazuhairnawan"
         git add .
         git commit -am "Auto update rclone config"
         git push
